function [fitresult, gof] = createFit(t, MSD_x_even_avg)
%CREATEFIT(T,MSD_X_EVEN_AVG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: MSD_x_even_avg
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Jul-2012 15:18:14


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, MSD_x_even_avg );

% Set up fittype and options.
ft = fittype( 'D_confined(x,L,va)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 0];
opts.StartPoint = [0.913375856139019 0.63235924622541];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'MSD_x_even_avg vs. t', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 't' );
ylabel( 'MSD_x_even_avg' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'untitled fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel( 't' );
ylabel( 'MSD_x_even_avg' );
grid on


